### ISSUE TITLE
Merge on demand

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#24]
A new bot task, that would be triggered by a command in a pull request comment.

**Command syntax**

`/ocabot merge (major|minor|patch)?`

**Actions performed**

- on merge command detected in PR comment
  - !!! check the author of the comment has the right to merge
    - is part of a team with write permission on the repo
    - or, is declared as maintainer in the manifest of all addons modified by the PR
  - rebase on main branch with autosquash
  - generate addon readme and setup.py
  - bump manifest version if (major|minor|patch), looking at all addons changed by the PR
  - push to a new branch named ``ocabot-merge-pr<pr>-to-<branch>`` (fail if that branch already exists)

- on red CI status on ``ocabot-merge-pr<pr>-to-<branch>`` branch
  - (ignore coverage/coveralls) 
  - add failed comment on PR
  - delete branch, exit

- on green CI status on ``ocabot-merge-pr<pr>-to-<branch>`` branch
  - push to main branch (--no-ff), if fail: rebase on main branch and force push ``ocabot-merge-pr<pr>-to-<branch>``, if rebase fails, delete branch and exit
  - delete branch ``ocabot-merge-pr<pr>-to-<branch>``
  - add a comment on the PR: *merged at sha*
  - close the PR
  - create wheel and publish to pypi, for the commit of our previous merge (to make sure a non .dev version goes to pypi if we bumped version)

**Attention point**
- makepot must somehow run before bumping the version: idea travis does makepot on `ocabot-merge-pr#`, and a local `msgmerge -U` is done before building the wheel so the translations in the wheel are aligned with the .pot.
- ~maybe we should allow makepot to run and push to PR branches~ => risk of merge conflict

**Tasks**

- [x] create main PR for this issue to which other subtasks can be contributed: #39
- [x] main method @sbidoul 
- [x] tie main method to command @sbidoul 
- [x] [function to bump manifest version](https://github.com/OCA/oca-github-bot/blob/cfe057f17a56a3a2a8827e11dda546546b780712/src/oca_github_bot/manifest.py#L65)
- [x] function to check if a github login has write access to the repo @fkantelberg 
- [x] webhook @fkantelberg 
- [x] function to detect addons modified by a PR, [start here](https://github.com/OCA/oca-github-bot/blob/cfe057f17a56a3a2a8827e11dda546546b780712/src/oca_github_bot/manifest.py#L93)
- [x] function to parse a comment and detect the merge command, returning {pr, target branch, version bump requested ('major'|'minor'|'patch'|None)}
- [x] functions to make the merge bot branch name from {pr, target branch} and parse the branch name 
to return {pr, target branch}
- [x] function to check if a github status webhook call is considered valid for merging (ignore coverage?)

**Comment by sbidoul** [comment]
@guewen what do you think?

**Comment by guewen** [comment]
Looks great!

**Comment by taifu** [comment]
This would be great!!!

**Comment by sbidoul** [comment]
@taifu the bump version will not be mandatory, because sometimes we want to merge several features before cutting a release.

**Comment by sbidoul** [comment]
Makepot and pypi publishing will be for another another PR.
